import type { Metadata } from "next";
import Header from '../components/header';
import "./globals.css";
import { Montserrat } from "next/font/google";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header  />

        <div>{children}</div>
        <div className="h-40"/>
      </body>
    </html>
  );
}
